[build]
  command = "npm run build"  
  functions = "./server"  

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run start"  

[context.backend]
  command = "npm run build" 
  functions = "./server"
  NODE_VERSION = "18"